Release/v0.10.0
fairlearn/fairlearn pull request #1327
Opened 2023-12-18 21:33 UTC by alliesaizan

## Description

## Tests

- [ ] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation

- [ ] no documentation changes needed
- [ ] user guide added or updated
- [ ] API docs added or updated
- [ ] example notebook added or updated

## Screenshots

2023-12-18 22:05 UTC, riedgar-ms approved these changes

2023-12-18 22:05 UTC, riedgar-ms commented on fairlearn/__init__.py
> +__version__ = "0.10.0"
Although.... shouldn't `main` be going to 0.11.0.dev0?

2023-12-18 22:06 UTC, riedgar-ms requested changes
Sorry, just noticed the branch

2023-12-18 22:08 UTC, riedgar-ms commented
@alliesaizan I don't think this is part of [the Release process](https://fairlearn.org/v0.9/contributor_guide/release.html) is it?

2023-12-18 22:55 UTC, alliesaizan commented
> @alliesaizan I don't think this is part of [the Release process](https://fairlearn.org/v0.9/contributor_guide/release.html) is it?

It looks like it's step 4, but let me know if I did something wrong: 
![image](https://github.com/fairlearn/fairlearn/assets/15962391/75e0ee58-b70a-42b8-ba46-d3c787c9b262)

2023-12-18 22:57 UTC, riedgar-ms commented
> > @alliesaizan I don't think this is part of [the Release process](https://fairlearn.org/v0.9/contributor_guide/release.html) is it?
> 
> It looks like it's step 4, but let me know if I did something wrong: ![image](https://private-user-images.githubusercontent.com/15962391/291428410-75e0ee58-b70a-42b8-ba46-d3c787c9b262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDA0ODQsIm5iZiI6MTcwMjk0MDE4NCwicGF0aCI6Ii8xNTk2MjM5MS8yOTE0Mjg0MTAtNzVlMGVlNTgtYjcwYS00MmI4LWJhNDYtZDNjNzg3YzliMjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIyNTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2RkOWYwZGQyNGJiZWYxNzI0NTg0NzM2NGQ0YTBlZTExYWY4YjQyYWY5MzdjZDFlMGM3ZjBkMDJiMzViMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCXOoc0PhbvQtdrwCc9TbVZXEVX55ikZli1oNNGx_IY)

Ahhh, that's supposed to be a PR which will merge onto the release branch to update the version. This PR is merging onto `main`

2023-12-19 00:08 UTC, alliesaizan commented
> > > @alliesaizan I don't think this is part of [the Release process](https://fairlearn.org/v0.9/contributor_guide/release.html) is it?
> > 
> > 
> > It looks like it's step 4, but let me know if I did something wrong: ![image](https://private-user-images.githubusercontent.com/15962391/291428410-75e0ee58-b70a-42b8-ba46-d3c787c9b262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDA0ODQsIm5iZiI6MTcwMjk0MDE4NCwicGF0aCI6Ii8xNTk2MjM5MS8yOTE0Mjg0MTAtNzVlMGVlNTgtYjcwYS00MmI4LWJhNDYtZDNjNzg3YzliMjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIyNTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2RkOWYwZGQyNGJiZWYxNzI0NTg0NzM2NGQ0YTBlZTExYWY4YjQyYWY5MzdjZDFlMGM3ZjBkMDJiMzViMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCXOoc0PhbvQtdrwCc9TbVZXEVX55ikZli1oNNGx_IY)
> 
> Ahhh, that's supposed to be a PR which will merge onto the release branch to update the version. This PR is merging onto `main`

Oh ok, so it looks like this is part of the release branch, so I should be able to close this PR and proceed with the remaining steps?

2023-12-19 00:17 UTC, riedgar-ms commented
> > > > @alliesaizan I don't think this is part of [the Release process](https://fairlearn.org/v0.9/contributor_guide/release.html) is it?
> > > 
> > > 
> > > It looks like it's step 4, but let me know if I did something wrong: ![image](https://private-user-images.githubusercontent.com/15962391/291428410-75e0ee58-b70a-42b8-ba46-d3c787c9b262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDA0ODQsIm5iZiI6MTcwMjk0MDE4NCwicGF0aCI6Ii8xNTk2MjM5MS8yOTE0Mjg0MTAtNzVlMGVlNTgtYjcwYS00MmI4LWJhNDYtZDNjNzg3YzliMjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIyNTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2RkOWYwZGQyNGJiZWYxNzI0NTg0NzM2NGQ0YTBlZTExYWY4YjQyYWY5MzdjZDFlMGM3ZjBkMDJiMzViMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCXOoc0PhbvQtdrwCc9TbVZXEVX55ikZli1oNNGx_IY)
> > 
> > 
> > Ahhh, that's supposed to be a PR which will merge onto the release branch to update the version. This PR is merging onto `main`
> 
> Oh ok, so it looks like this is part of the release branch, so I should be able to close this PR and proceed with the remaining steps?

I think so

2023-12-20 20:03 UTC, closed without merging