Fix equalized odds exceptions
fairlearn/fairlearn pull request #1433
Opened 2024-11-09 07:30 UTC by taharallouche

## Context
Hello ! This small PR has two commits:
- The first commit is the main one: it fixes the `agg` argument's validation in the two `equalized odds` functions, by raising instead of returning an exception. I added a couple of unit tests to cover that branch.
- The second commit is less important, it's just a follow-up on [my previous PR,](https://github.com/fairlearn/fairlearn/pull/1432) where I missed a couple of literals :sweat_smile: 

## Tests

- [ ] no new tests required
- [x] new tests added
- [ ] existing tests adjusted

## Documentation

- [x] no documentation changes needed
- [ ] user guide added or updated
- [ ] API docs added or updated
- [ ] example notebook added or updated

2024-11-09 07:30 UTC, taharallouche commented on test/unit/metrics/test_fairness_metrics.py
> +from contextlib import nullcontext as does_not_raise
Taken from [pytests's docs](https://docs.pytest.org/en/6.2.x/example/parametrize.html#parametrizing-conditional-raising)

2024-11-12 10:16 UTC, TamaraAtanasoska requested changes
Thanks for your PR! I left some comments which are mostly about missing docstrings and a suggestion to squash the added tests into one. Feel free to ping me when the changes are made so I can take a look again.

2024-11-12 10:16 UTC, TamaraAtanasoska commented on fairlearn/metrics/_fairness_metrics.py
> +    method: Literal["between_groups", "to_overall"] = "between_groups",
It would be great to also update the related docstring below to reflect the change

2024-11-12 10:16 UTC, TamaraAtanasoska commented on fairlearn/metrics/_fairness_metrics.py
> +    agg: Literal["worst_case", "mean"] = "worst_case",
a docstring change for both this updates is missing here too

2024-11-12 10:16 UTC, TamaraAtanasoska commented on fairlearn/metrics/_fairness_metrics.py
> +    agg: Literal["worst_case", "mean"] = "worst_case",
I believe the the docstring can be copied in all the relevant places, just mentioning these two here as well to not be missed.

2024-11-12 10:16 UTC, TamaraAtanasoska commented on test/unit/metrics/test_fairness_metrics.py
> +)
A suggestion: combining these two tests into one by having the function be a parameter too: 
`@pytest.mar.parametrize('method', [equalized_odds_difference, equalized_odds_ratio])`

2024-11-12 10:16 UTC, TamaraAtanasoska commented on fairlearn/metrics/_fairness_metrics.py
> +    sample_weight=None,
docstring

2024-11-12 10:16 UTC, TamaraAtanasoska commented on fairlearn/metrics/_fairness_metrics.py
> +    sample_weight=None,
docstring

2024-11-12 20:47 UTC, taharallouche commented
@TamaraAtanasoska Ready for a second round of reviews :pray:

2024-11-13 13:11 UTC, TamaraAtanasoska approved these changes
Thanks @taharallouche! Looks great now.

2024-11-13 13:11 UTC, merged